[project]
name = "Geopandas Test envs"
version = "0.1.0"
description = "Add a short description here"
authors = ["Matt Richards <mrichards7@outlook.com.au>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
_install = { cmd = "pixi install" }
test = "pytest"
# setup_geopandas = { cmd = "python -m pip install -e C:/Data/myDocuments/Code/geospatial/geopandas", cwd = "."}

# Editable installs
[pypi-dependencies]
geopandas = { path = "./geopandas_fork", editable = true }


[dependencies]
pip = ">=24.0,<25"
# pandas deps + optional deps
scipy = ">=1.12.0,<1.15"

matplotlib = ">=3.9.1,<3.10"
hypothesis = ">=6.107.0,<6.108"
meson-python = ">=0.16.0,<0.17"
pytz = ">=2024.1,<2025"
versioneer = ">=0.29,<1"
pyarrow = ">=16.1.0,<16.2"
pytest = ">=8.2.2,<8.3"
meson = ">=1.5.0,<1.6"
python-dateutil = ">=2.9.0,<2.10"
cython = ">=3.0.10,<3.1"

# utils
ipython = ">=8.14.0,<8.27"
jupyterlab = ">=4.2.3,<4.3"
pixi-pycharm = ">=0.0.6,<0.1"
pytest-xdist = ">=3.6.1,<3.7"
geodatasets = ">0.0.1"
# duckdb = ">=1.0"

# Geopandas deps (not required by pandas)
pyogrio = ">=0.8.0,<0.10"
shapely = ">=2.0.4,<2.1"
fiona = ">=1.9.6,<1.10"
pyproj = ">=3.6.1,<3.9"
# polars = ">=1.6.0,<1.7"
# sphinx = ">=7.4.7,<9"


[feature.pandas-dev.tasks]
# TODO setup pandas should declare inputs https://pixi.sh/v0.22.0/features/advanced_tasks/#caching
#  to get caching right
setup_pandas = {cmd = "python -m pip install -ve C:/Data/myDocuments/Code/python_other/data_science_open_source/pandas_new --no-build-isolation --config-settings builddir=\"builddir3\" --config-settings editable-verbose=true ", depends-on = ["_install"] }

[feature.pandas22.dependencies]
pandas = "==2.2.3"
numpy = "==1.26.4"
shapely = "==2.0.4"
pyproj = "==3.7.0"
pip = "==24.3.1"
pytest-cov = "==6.0.0"
sqlite = "==3.47.0"

[feature.pandas21.dependencies]
pandas = ">=2.1,<2.2"
numpy = ">=1.21,<2"
SQLalchemy = "<2.1"

[feature.pandas20.dependencies]
pandas = ">=2.0,<2.1"
numpy = ">=1.21,<2"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py310.dependencies]
python = "3.10.*"


[feature.docs.dependencies]
# These come mostly from doc/environment.yml
# required machinery
sphinx = "*"
pydata-sphinx-theme = "*"
numpydoc = "*"
pillow = "*"
sphinx-gallery = "*"
sphinx-toggleprompt = "*"
nbsphinx = "*"
myst-parser = "*"
# Optional deps needed to build docs
mapclassify = "*"
geopy = "*"
mock = "*"
pyepsg = "*"
jinja2 = "*"
doc2dash = "*"
matplotlib-scalebar = "*"
jupyter_client = "*"
ipykernel = "*"
folium = "*"
xyzservices = "*"

[feature.docs.tasks]
build_docs = { cmd = "make.bat html", cwd = "./geopandas_fork/doc"}
clean_docs = { cmd = "make.bat clean", cwd = "./geopandas_fork/doc"}



[environments]
# Note, only pull pandas-dev into a single version of python, due to cython / abi
# would need to create separate features with separate builddir specifications for different python versions
pandas-dev = ["pandas-dev", "py312"]
default = ["pandas22", "py312"]
docs = ["pandas22", "py311", "docs"] # TODO put back to py312 with scalebar

pd22 = ["pandas22", "py311"]
pd21 = ["pandas21", "py310"]
pd20 = ["pandas20", "py310"]
