[project]
name = "Geopandas Test envs"
version = "0.1.0"
description = "Add a short description here"
authors = ["Matt Richards <mrichards7@outlook.com.au>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
scipy = ">=1.14.0,<1.15"
pip = ">=24.0,<25"
matplotlib = ">=3.9.1,<3.10"
pytest-xdist = ">=3.6.1,<3.7"
hypothesis = ">=6.107.0,<6.108"
meson-python = ">=0.16.0,<0.17"
ipython = ">=8.26.0,<8.27"
pytz = ">=2024.1,<2025"
numpy = ">=2.0.0,<2.1"
versioneer = ">=0.29,<1"
python = "3.11.*"
pyarrow = ">=16.1.0,<16.2"
jupyterlab = ">=4.2.3,<4.3"
pytest = ">=8.2.2,<8.3"
pixi-pycharm = ">=0.0.6,<0.1"
meson = ">=1.5.0,<1.6"
python-dateutil = ">=2.9.0,<2.10"
cython = ">=3.0.10,<3.1"


